# Generated by Django 3.2.10 on 2024-09-11 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='booktableDb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bt_name', models.CharField(blank=True, max_length=50, null=True)),
                ('bt_time', models.IntegerField(blank=True, null=True)),
                ('bt_email', models.EmailField(blank=True, max_length=200, null=True)),
                ('bt_persons', models.CharField(blank=True, max_length=200, null=True)),
                ('bt_date', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='cartDb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart_username', models.CharField(blank=True, max_length=50, null=True)),
                ('cart_productname', models.CharField(blank=True, max_length=50, null=True)),
                ('cart_quantity', models.IntegerField(blank=True, null=True)),
                ('cart_price', models.IntegerField(blank=True, null=True)),
                ('cart_totalprice', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='checkoutDb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkout_username', models.CharField(blank=True, max_length=50, null=True)),
                ('checkout_email', models.EmailField(blank=True, max_length=50, null=True)),
                ('checkout_place', models.CharField(blank=True, max_length=50, null=True)),
                ('checkout_address', models.TextField(blank=True, null=True)),
                ('checkout_Phone', models.IntegerField(blank=True, null=True)),
                ('checkout_message', models.TextField(blank=True, null=True)),
                ('checkout_overall_total', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='contactDb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('con_name', models.CharField(blank=True, max_length=50, null=True)),
                ('con_number', models.IntegerField(blank=True, null=True)),
                ('con_message', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='reviewDb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rev_name', models.CharField(blank=True, max_length=50, null=True)),
                ('rev_email', models.EmailField(blank=True, max_length=200, null=True)),
                ('rev_message', models.CharField(blank=True, max_length=200, null=True)),
                ('rev_rate', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='signUpDb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('su_email', models.EmailField(blank=True, max_length=100, null=True)),
                ('su_username', models.CharField(blank=True, max_length=50, null=True)),
                ('su_password', models.CharField(blank=True, max_length=100, null=True)),
                ('su_confirmpassword', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
