# Generated by Django 5.0.6 on 2024-05-23 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contactDb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('con_name', models.CharField(blank=True, max_length=50, null=True)),
                ('con_number', models.IntegerField(blank=True, null=True)),
                ('con_message', models.IntegerField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
