# Generated by Django 5.0.6 on 2024-05-28 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontendfood', '0002_alter_contactdb_con_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='signUpDb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('su_email', models.EmailField(blank=True, max_length=100, null=True)),
                ('su_username', models.CharField(blank=True, max_length=50, null=True)),
                ('su_password', models.CharField(blank=True, max_length=100, null=True)),
                ('su_confirmpassword', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
