# Generated by Django 3.2.10 on 2024-09-11 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontendfood', '0002_alter_booktabledb_bt_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='booktabledb',
            name='bt_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
