# Generated by Django 5.0.6 on 2024-05-31 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontendfood', '0003_signupdb'),
    ]

    operations = [
        migrations.CreateModel(
            name='cartDb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart_username', models.CharField(blank=True, max_length=50, null=True)),
                ('cart_productname', models.CharField(blank=True, max_length=50, null=True)),
                ('cart_quantity', models.IntegerField(blank=True, null=True)),
                ('cart_totalprice', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
