# Generated by Django 3.2.10 on 2024-09-11 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontendfood', '0003_booktabledb_bt_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booktabledb',
            name='bt_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='booktabledb',
            name='bt_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
