# Generated by Django 5.0.6 on 2024-06-01 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontendfood', '0004_cartdb'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartdb',
            name='cart_price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
