# Generated by Django 3.2.10 on 2024-09-11 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='fbProductDb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_code', models.CharField(blank=True, max_length=50, null=True)),
                ('p_category', models.CharField(blank=True, max_length=50, null=True)),
                ('p_name', models.CharField(blank=True, max_length=50, null=True)),
                ('p_price', models.IntegerField(blank=True, null=True)),
                ('p_description', models.CharField(blank=True, max_length=200, null=True)),
                ('p_picture', models.ImageField(blank=True, null=True, upload_to='product_pic')),
            ],
        ),
        migrations.CreateModel(
            name='fdCategoryDb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_name', models.CharField(blank=True, max_length=50, null=True)),
                ('c_description', models.CharField(blank=True, max_length=200, null=True)),
                ('c_picture', models.ImageField(blank=True, null=True, upload_to='category_pic')),
            ],
        ),
    ]
