# Generated by Django 5.0.6 on 2024-05-21 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='fdCategoryDb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_name', models.CharField(blank=True, max_length=50, null=True)),
                ('c_description', models.CharField(blank=True, max_length=200, null=True)),
                ('c_picture', models.ImageField(blank=True, null=True, upload_to='category_pic')),
            ],
        ),
    ]
