# Generated by Django 5.1.1 on 2024-09-13 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendfood', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fbproductdb',
            name='p_picture',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='fdcategorydb',
            name='c_picture',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
