# Generated by Django 5.0.6 on 2024-05-22 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendfood', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='fbProductDb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_code', models.CharField(blank=True, max_length=50, null=True)),
                ('p_category', models.CharField(blank=True, max_length=50, null=True)),
                ('p_name', models.CharField(blank=True, max_length=50, null=True)),
                ('p_price', models.IntegerField(blank=True, null=True)),
                ('p_description', models.CharField(blank=True, max_length=200, null=True)),
                ('p_picture', models.ImageField(blank=True, null=True, upload_to='product_pic')),
            ],
        ),
    ]
